countries = ['afghanistan', 'aland islands', 'albania',
             'algeria', 'american samoa', 'andorra', 'angola',
             'anguilla', 'antarctica', 'antigua and barbuda',
             'argentina', 'armenia', 'aruba', 'australia', 'austria',
             'azerbaijan', 'bahamas', 'bahrain', 'bangladesh',
             'barbados', 'belarus', 'belgium', 'belize', 'benin',
             'bonaire, sint eustatius and saba', 'bosnia and herzegovina',
             'botswana', 'bouvet island', 'brazil',
             'brunei darussalam', 'bulgaria', 'burkina faso', 'burundi',
             'cabo verde', 'cambodia', 'cameroon', 'canada',
             'cayman islands', 'central african republic',
             'chad', 'chile', 'china', 'christmas island',
             'cocos islands', 'colombia',
             'comoros', 'congo',
             'congo', 'cook islands', 'costa rica',
             "cote d'ivoire", 'croatia', 'cuba', 'curacao', 'cyprus',
             'czechia', 'denmark', 'djibouti', 'dominica',
             'dominican republic', 'ecuador', 'egypt', 'el salvador',
             'equatorial guinea', 'eritrea', 'estonia', 'ethiopia',
             'falkland islands', 'faroe islands',
             'fiji', 'finland', 'france', 'french guiana', 'french polynesia',
             'french southern territories', 'gabon', 'gambia',
             'georgia', 'germany', 'ghana', 'gibraltar', 'greece', 'greenland',
             'grenada', 'guadeloupe', 'guam', 'guatemala', 'guernsey', 'guinea',
             'guinea-bissau', 'guyana', 'haiti',
             'heard island and mcdonald islands', 'holy see', 'honduras',
             'hong kong', 'hungary', 'iceland', 'india', 'indonesia',
             'iran', 'iraq', 'ireland', 'isle of man',
             'israel', 'italy', 'jamaica', 'japan', 'jersey', 'jordan',
             'kazakhstan', 'kenya', 'kiribati',
             "korea (the democratic people's republic of)",
             'korea (the republic of)', 'kuwait', 'kyrgyzstan',
             "lao people's democratic republic", 'latvia',
             'lebanon', 'lesotho', 'liberia', 'libya', 'liechtenstein',
             'lithuania', 'luxembourg', 'macao',
             'macedonia',
             'madagascar', 'malawi', 'malaysia', 'maldives', 'mali',
             'malta', 'marshall islands', 'martinique', 'mauritania',
             'mauritius', 'mayotte', 'mexico',
             'micronesia', 'moldova',
             'monaco', 'mongolia', 'montenegro', 'montserrat', 'morocco',
             'mozambique', 'myanmar', 'namibia', 'nauru', 'nepal',
             'netherlands', 'new caledonia', 'new zealand', 'nicaragua',
             'niger', 'nigeria', 'niue', 'norfolk island',
             'northern mariana islands', 'norway', 'oman',
             'pakistan', 'palau', 'palestine, state of', 'panama',
             'papua new guinea', 'paraguay', 'peru', 'philippines',
             'pitcairn', 'poland', 'portugal', 'puerto rico', 'qatar',
             'reunion', 'romania', 'russian federation', 'rwanda',
             'saint barthelemy', 'saint helena, ascension and tristan da cunha',
             'saint kitts and nevis', 'saint lucia', 'saint martin',
             'saint pierre and miquelon', 'saint vincent and the grenadines',
             'samoa', 'san marino', 'sao tome and principe', 'saudi arabia',
             'senegal', 'serbia', 'seychelles', 'sierra leone', 'singapore',
             'sint maarten', 'slovakia', 'slovenia', 'solomon islands',
             'somalia', 'south africa', 'south georgia and the south sandwich islands',
             'south sudan', 'spain', 'sri lanka', 'sudan', 'suriname',
             'svalbard and jan mayen', 'swaziland', 'sweden', 'switzerland',
             'syrian arab republic', 'taiwan', 'tajikistan',
             'tanzania, united republic of', 'thailand', 'timor-leste', 'togo',
             'tokelau', 'tonga', 'trinidad and tobago', 'tunisia', 'turkey',
             'turkmenistan', 'turks and caicos islands', 'tuvalu',
             'uganda', 'ukraine', 'united arab emirates',
             'united kingdom of great britain and northern ireland',
             'united states minor outlying islands',
             'united states of america', 'uruguay',
             'uzbekistan', 'vanuatu', 'venezuela',
             'viet nam', 'virgin islands', 'wallis and futuna',
             'western sahara*', 'yemen', 'zambia', 'zimbabwe'
             ]
